name: Swift

on: [push]

jobs:
    linux-swift:
        name: Linux x86_64
        runs-on: ubuntu-20.04
        container: swift:5.6.1-focal
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Swift Version
          run: swift --version
        - name: Build (Debug)
          run: swift build -c debug
        - name: Build (Release)
          run: swift build -c release
